### ISSUE TITLE
postfix queue file write error after container restart

### ISSUE THREAD

**Issue by MHofer** [iredmail/dockerized#107]
after restart the container the mailserver ist dead, postfix error ist "queue file write error" 
after create the container it works

**Comment by iredmail** [comment]
Did you lose the mounted volumes after restart?

**Comment by MHofer** [comment]
the folders are connected but they are empty

after a recreation they also remain empty but the server is working

**Comment by tpimh** [comment]
For some reason, the restart always fails. I just first remove the container (preserving the volumes), then recreate it, and it starts well.

**Comment by MHofer** [comment]
I had an error with the volumes, which I have corrected, but I still have to recreate the iRedmail container after restarting the server.

**Comment by tpimh** [comment]
I just tried with Portainer, and I can reproduce the issue.

Here is my slightly redacted docker-compose yaml:

```yaml
version: '3.8'
services:
  mailserver:
    image: iredmail/mariadb:stable
    container_name: 'iredmail'
    restart: always
    hostname: mail.example.org
    environment:
      TZ: Europe/Helsinki
      HOSTNAME: mail.example.org
      FIRST_MAIL_DOMAIN: example.org
      FIRST_MAIL_DOMAIN_ADMIN_PASSWORD: redacted
      MLMMJADMIN_API_TOKEN: redacted
      ROUNDCUBE_DES_KEY: redacted
      MYSQL_USE_RANDOM_PASSWORDS: "NO"
      USE_AUTOCONFIG: "YES"
      MYSQL_ROOT_PASSWORD: redacted
      VMAIL_DB_PASSWORD: redacted
      VMAIL_DB_ADMIN_PASSWORD: redacted
      AMAVISD_DB_PASSWORD: redacted
      ROUNDCUBE_DB_PASSWORD: redacted
      IREDAPD_DB_PASSWORD: redacted
      IREDADMIN_DB_PASSWORD: redacted
      FAIL2BAN_DB_PASSWORD: redacted
      SA_BAYES_DB_PASSWORD: redacted
    volumes:
      - iredmail_backup:/var/vmail/backup
      - iredmail_mailboxes:/var/vmail/vmail1
      - iredmail_mlmmj:/var/vmail/mlmmj
      - iredmail_mlmmj-archive:/var/vmail/mlmmj-archive
      - iredmail_imapsieve_copy:/var/vmail/imapsieve_copy
      - iredmail_custom:/opt/iredmail/custom
      - iredmail_ssl:/opt/iredmail/ssl
      - iredmail_mysql:/var/lib/mysql
      - iredmail_clamav:/var/lib/clamav
      - iredmail_sa_rules:/var/lib/spamassassin
      - iredmail_postfix_queue:/var/spool/postfix
volumes:
  iredmail_backup:
  iredmail_mailboxes:
  iredmail_mlmmj:
  iredmail_mlmmj-archive:
  iredmail_imapsieve_copy:
  iredmail_custom:
  iredmail_ssl:
  iredmail_mysql:
  iredmail_clamav:
  iredmail_sa_rules:
  iredmail_postfix_queue:
```
