### ISSUE TITLE
install: can't create directory ...  : Operation not permitted

### ISSUE THREAD

**Issue by posesco** [iredmail/dockerized#30]
Thank you for your efforts to maintain this software.

I found these errors in the installation:

```
[iRedMail] [Entrypoint] /docker/entrypoints/postfix.sh
install: can't create directory '/opt/iredmail/custom/postfix/disclaimer': Operation not permitted
```
```
[iRedMail] [Entrypoint] /docker/entrypoints/antispam.sh
install: can't create directory '/opt/iredmail/custom/amavisd/dkim': Operation not permitted
```
I suspect that these are permissions that are assigned in the bash routines: 
[postfix.sh](https://github.com/iredmail/dockerized/blob/master/entrypoints/postfix.sh)
[antispam.sh](https://github.com/iredmail/dockerized/blob/master/entrypoints/antispam.sh)

I appreciate your help solving this error

**Comment by iredmail** [comment]
It’s not about the scripts, but permission of the data directory or volume you assigned to this container.

**Comment by posesco** [comment]
> It’s not about the scripts, but permission of the data directory or volume you assigned to this container.

How can I find a solution to this problem?

**Comment by iredmail** [comment]
Please show us the full docker command you ran.

**Comment by posesco** [comment]
> Please show us the full docker command you ran.

Hello, this is what I run.

```
version: '3.8'
services:
  mail:
    container_name: SERVER_MAIL
    hostname: mail.mydns.com
    image: iredmail/mariadb:stable
    volumes:
      - ./mail/backup:/var/vmail/backup
      - ./mail/mailboxes:/var/vmail/vmail1
      - ./mail/mlmmj:/var/vmail/mlmmj
      - ./mail/mlmmj-archive:/var/vmail/mlmmj-archive
      - ./mail/imapsieve_copy:/var/vmail/imapsieve_copy
      - ./mail/mysql:/var/lib/mysql
      - ./mail/clamav:/var/lib/clamav
      - ./mail/sa_rules:/var/lib/spamassassin
      - ./mail/postfix_queue:/var/spool/postfix
      - ./mail/custom:/opt/iredmail/custom
      - ./mail/ssl:/opt/iredmail/ssl
    ports:
      - '80:80'
      - '443:443' 
      - '110:110' 
      - '995:995' 
      - '143:143'
      - '993:993'
      - '25:25'
      - '465:465' 
      - '587:587'
    env_file: ./.env
    restart: unless-stopped
    networks: 
      mail_net:
networks:
  mail_net:
```
And this is the content of file .env

```
TZ=America/Bogota
HOSTNAME=mail.mydns.com
FIRST_MAIL_DOMAIN=mydns.com
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=Cq[oEG:7
MLMMJADMIN_API_TOKEN=iWnJCcRoWihTCENcTzsQl5i09w70IYMjgeKGf+FY/+A=
ROUNDCUBE_DES_KEY=1420BOto0oTAggk+C4w9QasDAqDhF9XP
POSTMASTER_EMAIL=postmaster@mydns.com
MYSQL_ROOT_PASSWORD=UaVtmhXyUq$4
```
