### ISSUE TITLE
Emails from outside are not receiving

### ISSUE THREAD

**Issue by dpineiden** [iredmail/dockerized#48]
Hi!

I've installed and configured the iredmail container.

What works:

- all with ssl
- send mails between domain users (a->b, b->a)
- send mails to other emails
- configure clients, (with autodiscover also)
- all ports opened
What I miss?

best regards!

But can't send emails from gmail or another.

**Comment by iredmail** [comment]
Do you have correct DNS records for your server hostname and mail domain names?

**Comment by dpineiden** [comment]
Yes, 

The MX; SPF, DKIM, DMARC and autodiscovers works. Tried the dig commando and works.

Thanks for the fast answer :)

Maybe there are other env variable to set and open the networks... I don't know yet.

Best regards

**Comment by dpineiden** [comment]
Whit this:

dig tecnocomunes.org MX +short

shows an answer...

**Comment by dpineiden** [comment]
From google, shows this two errors:
 DNS Error: 15154937 DNS type 'mx' lookup of tecnocomunes.org responded with code SERVFAIL 

The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [mail.tecnocomunes.org. 78.128.81.155: FAILED_PRECONDITION: connect error (111): Connection refused] 

But if i try to connect to port 25 using telnet is ok, and also dig or lookup :S

**Comment by dpineiden** [comment]
It seems all records on DNS all ok, I can send mails from accounts from same domain, but reject yer from outside. What can be? any  help?

**Comment by iredmail** [comment]
> It seems all records on DNS all ok, I can send mails from accounts from same domain

Many DNS vendors take up to 2 hours to publish new DNS records, i guess you didn't wait that long, and now it works.

> but reject yer from outside. What can be? any help?

No log, no help. :(
We need related log for troubleshooting.

**Comment by dpineiden** [comment]
Well, here i have the info

In localhost, the port 25/tcp is open

```
25/tcp ALLOW Anywhere
2525/tcp ALLOW Anywhere
25/udp ALLOW Anywhere
2525/udp ALLOW Anywhere
25/tcp (v6) ALLOW Anywhere (v6)
2525/tcp (v6) ALLOW Anywhere (v6)
25/udp (v6) ALLOW Anywhere (v6)
2525/udp (v6) ALLOW Anywhere (v6)
```
And a netstat command:

```
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      17278/exim4         
tcp6       0      0 ::1:25                  :::*                    LISTEN      17278/exim4
```

On outside, I have closed the port.

```
nmap mail.tecnocomunes.org -p 25 -PN
Starting Nmap 7.70 ( https://nmap.org ) at 2021-02-25 23:31 -03
Nmap scan report for mail.tecnocomunes.org (78.128.81.155)
Host is up (0.39s latency).
DNS record for 78.128.81.155: proyectos

PORT STATE SERVICE
25/tcp closed smtp
```
Nmap done: 1 IP address (1 host up) scanned in 5.51 seconds

The docker-compose is pretty standar:

```
version: '3.5'
services:
#
# IREDMAIL
#
  iredmail: 
    image: iredmail/mariadb:stable
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: iredmail
    hostname: mail
    domainname: tecnocomunes.org
    env_file:  ./iredmail-docker.conf
    volumes:
    - /iredmail/data/backup:/var/vmail/backup 
    - /iredmail/data/mailboxes:/var/vmail/vmail1 
    - /iredmail/data/mlmmj:/var/vmail/mlmmj 
    - /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive 
    - /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy 
    - /iredmail/data/custom:/opt/iredmail/custom 
    - /iredmail/data/ssl:/opt/iredmail/ssl 
    - /iredmail/data/mysql:/var/lib/mysql 
    - /iredmail/data/clamav:/var/lib/clamav 
    - /iredmail/data/sa_rules:/var/lib/spamassassin 
    - /iredmail/data/postfix_queue:/var/spool/postfix 
    ports: 
      - 2080:80
      - 20443:443
      - 25:25
      - 587:587
      - 110:110
      - 143:143
      - 993:993
      - 995:995
      - 465:465
#
```


About the logs in particular, i cannot find some inside the container. Where are these?
